const $=s=>document.querySelector(s);let timer=null;const state={api:sessionStorage.edhApi||'',key:sessionStorage.edhKey||'',run:sessionStorage.edhRun||''};$('#api').value=state.api;$('#key').value=state.key;
async function call(path,options={}){const response=await fetch(state.api.replace(/\/$/,'')+path,{...options,headers:{Authorization:'Bearer '+state.key,'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}const pretty=v=>JSON.stringify(v||{},null,2),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function runs(){const data=await call('/api/runs'),select=$('#runs');select.innerHTML=data.runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id)} · ${esc(r.state)}</option>`).join('');if(state.run&&data.runs.some(r=>r.id===state.run))select.value=state.run;else state.run=select.value||'';if(state.run)await refresh()}
async function refresh(){if(!state.run)return;const s=await call('/api/runs/'+state.run);sessionStorage.edhRun=state.run;render(s);$('#connection').textContent='Live · '+s.revision;$('#connection').style.color='var(--mint)'}
function render(s){
 const st=s.status||{},request=st.request||{},a=s.next_action||{},ps=st.public_state||{};
 $('#headline').textContent=`Game ${String(s.game).padStart(2,'0')} · ${s.state}`;$('#subhead').textContent=`Active: ${ps.active||'—'} · Priority/decision: ${request.actor||a.actor||'—'} · ${request.kind||a.kind||'No pending action'}`;$('#turn').textContent=ps.round!==undefined?`R${ps.round} · T${ps.turn_number||0} · ${ps.phase||''}`:'';
 $('#metrics').innerHTML=[['Decisions',st.decision_count||0],['Game',s.game],['Host',s.host.alive?'online':'stopped'],['Learning',s.config.learning_enabled===false?'off':'on']].map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');$('#table').innerHTML=Object.entries(ps.players||{}).map(([name,p])=>`<div class="event"><strong>${esc(name)}</strong><span>${esc(p.life??'')} life · ${esc((p.battlefield||[]).length)} permanents · ${esc(p.hand?.length??p.hand_count??'?')} cards</span></div>`).join('')||'<p>No checkpoint yet.</p>';
 $('#next').textContent=pretty(request.actor?request:a);$('#events').innerHTML=(s.events||[]).slice(-20).reverse().map((e,i)=>`<div class="event"><span>${esc(e.event||e.kind||e.decision_id||'#'+i)}</span><code>${esc(e.summary||e.choice||e.action||JSON.stringify(e).slice(0,240))}</code></div>`).join('')||'<p>No accepted events yet.</p>';$('#config').textContent=pretty(s.config);$('#host').textContent=pretty(s.host)+'\n\n'+s.auth_mode;$('#status').textContent=pretty(st);$('#messages').textContent=s.messageboard||'No public messages have been posted.';
 const players=Object.keys(s.operator||{}),seat=$('#seatSelect'),prior=seat.value;seat.innerHTML=players.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');if(players.includes(prior))seat.value=prior;$('#player').textContent=players.length?s.operator[seat.value||players[0]]:'Operator snapshots appear after the first checkpoint.';seat.onchange=()=>$('#player').textContent=s.operator[seat.value];
}
async function action(fn){try{$('#error').textContent='';await fn()}catch(e){$('#error').textContent=e.message}}
$('#connectButton').onclick=()=>action(async()=>{state.api=$('#api').value.trim();state.key=$('#key').value.trim();sessionStorage.edhApi=state.api;sessionStorage.edhKey=state.key;await runs();$('#connect').hidden=true;$('#app').hidden=false;clearInterval(timer);timer=setInterval(()=>action(refresh),2000)});$('#runs').onchange=()=>{state.run=$('#runs').value;refresh()};$('#refresh').onclick=()=>action(refresh);$('#start').onclick=()=>action(async()=>{await call(`/api/runs/${state.run}/start`,{method:'POST',body:'{}'});await refresh()});$('#pause').onclick=()=>action(async()=>{await call(`/api/runs/${state.run}/pause`,{method:'POST',body:'{}'});await refresh()});
$('#create').onclick=()=>action(async()=>{const body={id:$('#runId').value.trim()||undefined,games:+$('#games').value,seed_start:+$('#seed').value,max_rounds:+$('#rounds').value,learning:$('#learning').value,async_diplomacy:$('#diplomacy').checked},made=await call('/api/runs',{method:'POST',body:JSON.stringify(body)});state.run=made.id;await runs();document.querySelector('[data-tab="live"]').click()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab)});
